sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dhagash/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dhagash/docker-react npm run test

